<?php

namespace JobBundle\Repository;

/**
 * FurloughRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurloughRepository extends \Doctrine\ORM\EntityRepository
{
}
