<?php

namespace JobBundle\Repository;

use Doctrine\ORM\Mapping;
use JobBundle\Entity\Plan;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct($em, Mapping\ClassMetadata $metaData=null)
    {
        parent::__construct($em,
            $metaData=null?
                new  Mapping\ClassMetadata(Plan::class) : $metaData
        );
    }
    public function create(Plan $plan){
        $this->_em->persist(Plan::class);
        $this->_em->flush();
        return true;
    }
}
