<?php

namespace JobBundle\Repository;

use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use JobBundle\Entity\Plan;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct($em, Mapping\ClassMetadata $metaData=null)
    {
        parent::__construct($em,
            $metaData=null?
                new  Mapping\ClassMetadata(Plan::class) : $metaData
        );
    }

    /**
     * @param Plan $plan
     * @return bool
     */
    public function create(Plan $plan){
        try{
            $this->_em->persist($plan);
            $this->_em->flush();
            return true;
        }catch(OptimisticLockException $ex){
            return false;
        }
    }
}
